version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      "POSTGRES_PASSWORD": "judomythe"
      "POSTGRES_USER": "judo"
      "POSTGRES_DB": "judo"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    image: back_judo:0.1
    build: ./back_judo
    links:
      - db:db
    volumes:
      - ./back_judo:/opt/workspace
    ports:
      - 5000:5000
    environment:
      "POSTGRES_PASSWORD": "judomythe"
      "POSTGRES_USER": "judo"
      "POSTGRES_DB": "judo"
